name: Release
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}